helm:
  global:
      cluster:
        type: 'eks'
      fqdn: 'cluster1'
      aws:
        profile: 'default'
      region:
        location: 'eu-west-1'
infrastructure:
  helmfile:
    version: "v0.0.1"
