---
compositions:
  order:
    terraform:
      - account
      - network
      - cluster
      - spinnaker
    helmfile:
      - helmfiles
terraform:
  local_path: '/home/bmutziu/work/k8s/kompos'
  root_path: '.'
  repo:
    name: 'terraform-stack'
    url: "git@github.com:bmutziu/terraform-stack.git"
helmfile:
  local_path: '/home/bmutziu/work/k8s/kompos'
  root_path: '.'
  repo:
    name: 'helmfile-releases'
    url: "git@github.com:bmutziu/helmfiles-releases.git"
nix: true
vault:
  enabled: true
  svc_ldap_user: demo
  svc_ldap_user_role: secret
  url: bmutziu.me
  vault_namespace: parameter
